# Generated by Django 3.1.1 on 2020-11-26 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_animal', models.CharField(choices=[('O', 'Ovino'), ('E', 'Equino'), ('A', 'Avicola')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ovino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('HEMBRA', 'Hembra'), ('MACHO', 'Macho')], default='MACHO', max_length=6)),
                ('cant_de_dientes', models.IntegerField()),
                ('categoria_por_diente', models.CharField(choices=[('COR', 'Cordero'), ('BOR', 'Borrego'), ('OVJ', 'Oveja'), ('CAR', 'Carnero'), ('OVJ V', 'Oveja vieja'), ('CAR V', 'Carnero viejo')], default='OVJ', max_length=5)),
                ('fecha_de_registro', models.DateField()),
                ('fecha_de_nacimiento', models.DateField()),
                ('PDP', models.BooleanField(default=False)),
                ('peso', models.FloatField()),
                ('padre', models.CharField(blank=True, max_length=10)),
                ('madre', models.CharField(blank=True, max_length=10)),
                ('calidad_de_lana', models.IntegerField()),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.raza')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('Desde', models.DateTimeField()),
                ('Hasta', models.DateTimeField()),
                ('area_de_Trabajo', models.CharField(choices=[('QUINTA', 'Quinta'), ('ANIMALES', 'Animales'), ('PERSONAL', 'Personal'), ('COMPRA', 'Compra'), ('MANTENIMIENTO', 'Mantenimiento'), ('OTRA', 'Otra')], default='OTRA', max_length=13)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Equino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('color_pelaje', models.CharField(max_length=20)),
                ('condicion', models.CharField(max_length=30)),
                ('fecha_De_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('HEMBRA', 'Hembra'), ('MACHO', 'Macho')], default='HEMBRA', max_length=6)),
                ('causa_de_muerte', models.CharField(blank=True, max_length=30)),
                ('manada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.manada')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.raza')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Energia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Molino,Panel Solar,etc.', max_length=30)),
                ('fecha_de_instalacion', models.DateField()),
                ('estado', models.CharField(choices=[('BUEN_ENSTADO', 'Buen estado'), ('MAL_ESTADO', 'Mal estado'), ('EN_MANTENIMIENTO', 'En mantenimiento')], default='BUEN_ENSTADO', max_length=16)),
                ('descripcion_del_estado', models.CharField(blank=True, max_length=200)),
                ('fecha_De_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.fecha')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Avicola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('HEMBRA', 'Hembra'), ('MACHO', 'Macho')], default='HEMBRA', max_length=6)),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.raza')),
            ],
        ),
        migrations.CreateModel(
            name='Alambrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_kilometros', models.FloatField()),
                ('materiales', models.CharField(max_length=40)),
                ('estado', models.CharField(choices=[('BUEN_ENSTADO', 'Buen estado'), ('MAL_ESTADO', 'Mal estado'), ('EN_MANTENIMIENTO', 'En mantenimiento')], default='BUEN_ENSTADO', max_length=16)),
                ('seccion', models.ManyToManyField(to='py.Seccion')),
            ],
        ),
    ]
