# Generated by Django 3.1.1 on 2020-10-29 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_compra', models.DateField()),
                ('descripcion_de_cant_individual', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiguedad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_entrega', models.DateField()),
                ('fecha_de_devolucion', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.alimento')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.insumo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(max_length=500)),
                ('consecuencia', models.CharField(max_length=500)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.personal')),
            ],
        ),
    ]
