# Generated by Django 3.1.1 on 2020-10-30 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py', '0002_alimento_amonestacion_insumo_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.direccion')),
            ],
        ),
        migrations.RemoveField(
            model_name='personal',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='personal',
            name='rol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Telefono',
        ),
        migrations.AddField(
            model_name='p_d',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.personal'),
        ),
        migrations.AddField(
            model_name='personal',
            name='direccion',
            field=models.ManyToManyField(through='py.p_d', to='py.Direccion'),
        ),
    ]
