# Generated by Django 3.1.1 on 2020-10-30 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py', '0003_auto_20201029_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=9)),
                ('marca', models.CharField(max_length=20)),
                ('tipo_motor', models.CharField(max_length=20)),
                ('tipo_rodado', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='personal',
            name='direccion',
        ),
        migrations.AddField(
            model_name='personal',
            name='direcciones',
            field=models.ManyToManyField(to='py.Direccion'),
        ),
        migrations.DeleteModel(
            name='p_d',
        ),
        migrations.AddField(
            model_name='rodados',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.personal'),
        ),
    ]
