# Generated by Django 3.1.1 on 2020-10-30 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py', '0004_auto_20201029_2154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rodados',
            new_name='Rodado',
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('rol', models.CharField(max_length=50)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.direccion')),
            ],
        ),
        migrations.AlterField(
            model_name='amonestacion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.persona'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.persona'),
        ),
        migrations.AlterField(
            model_name='rodado',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.persona'),
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
