# Generated by Django 3.1.1 on 2020-11-05 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py', '0007_auto_20201104_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='py.direccion'),
            preserve_default=False,
        ),
    ]
