# Generated by Django 3.1.1 on 2020-11-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py', '0008_auto_20201105_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='antiguedad',
        ),
        migrations.AddField(
            model_name='alambrado',
            name='estado',
            field=models.CharField(choices=[('BUEN_ENSTADO', 'Buen estado'), ('MAL_ESTADO', 'Mal estado'), ('EN_MANTENIMIENTO', 'En mantenimiento')], default='BUEN_ENSTADO', max_length=16),
        ),
        migrations.AddField(
            model_name='fecha',
            name='area_de_Trabajo',
            field=models.CharField(choices=[('QUINTA', 'Quinta'), ('ANIMALES', 'Animales'), ('PERSONAL', 'Personal'), ('COMPRA', 'Compra'), ('MANTENIMIENTO', 'Mantenimiento'), ('OTRA', 'Otra')], default='OTRA', max_length=13),
        ),
        migrations.AlterField(
            model_name='amonestacion',
            name='razon',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='energia',
            name='estado',
            field=models.CharField(choices=[('BUEN_ENSTADO', 'Buen estado'), ('MAL_ESTADO', 'Mal estado'), ('EN_MANTENIMIENTO', 'En mantenimiento')], default='BUEN_ENSTADO', max_length=16),
        ),
        migrations.AlterField(
            model_name='ovino',
            name='madre',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ovino',
            name='padre',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ovino',
            name='raza',
            field=models.CharField(choices=[('CORMO', 'Cormo'), ('SUFFOLK', 'Suffolk')], default='CORMO', max_length=16),
        ),
        migrations.AlterField(
            model_name='rodado',
            name='estado',
            field=models.CharField(choices=[('BUEN_ENSTADO', 'Buen estado'), ('MAL_ESTADO', 'Mal estado'), ('EN_MANTENIMIENTO', 'En mantenimiento')], default='BUEN_ENSTADO', max_length=16),
        ),
    ]
