# Generated by Django 3.1.1 on 2020-11-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py', '0009_auto_20201105_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fecha',
            old_name='horadesde',
            new_name='Desde',
        ),
        migrations.RenameField(
            model_name='fecha',
            old_name='horahasta',
            new_name='Hasta',
        ),
        migrations.RemoveField(
            model_name='fecha',
            name='fecha',
        ),
    ]
