# Generated by Django 3.1.1 on 2020-11-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py', '0010_auto_20201105_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avicola',
            name='raza',
        ),
        migrations.AddField(
            model_name='ovino',
            name='sexo',
            field=models.CharField(choices=[('HEMBRA', 'Hembra'), ('MACHO', 'Macho')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equino',
            name='sexo',
            field=models.CharField(choices=[('HEMBRA', 'Hembra'), ('MACHO', 'Macho')], max_length=6),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
