# Generated by Django 3.1.1 on 2020-11-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py', '0011_auto_20201106_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='avicola',
            name='raza',
            field=models.CharField(default='ponedora', max_length=30),
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('HEMBRA', 'Hembra'), ('MACHO', 'Macho')], default='MACHO', max_length=6),
        ),
        migrations.AlterField(
            model_name='avicola',
            name='sexo',
            field=models.CharField(choices=[('HEMBRA', 'Hembra'), ('MACHO', 'Macho')], default='HEMBRA', max_length=6),
        ),
    ]
