# Generated by Django 3.1.1 on 2020-11-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py', '0012_auto_20201106_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equino',
            name='sexo',
            field=models.CharField(choices=[('HEMBRA', 'Hembra'), ('MACHO', 'Macho')], default='HEMBRA', max_length=6),
        ),
        migrations.AlterField(
            model_name='ovino',
            name='sexo',
            field=models.CharField(choices=[('HEMBRA', 'Hembra'), ('MACHO', 'Macho')], default='MACHO', max_length=6),
        ),
    ]
