# Generated by Django 3.1.1 on 2020-11-07 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py', '0013_auto_20201106_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='persona',
            new_name='empleado',
        ),
        migrations.RemoveField(
            model_name='rodado',
            name='persona',
        ),
        migrations.AddField(
            model_name='rodado',
            name='Conductores',
            field=models.ManyToManyField(to='py.Persona'),
        ),
        migrations.AlterField(
            model_name='alambrado',
            name='materiales',
            field=models.CharField(help_text='Madera,Alambre,Malla,etc.', max_length=200),
        ),
        migrations.AlterField(
            model_name='amonestacion',
            name='consecuencia',
            field=models.CharField(help_text='Suspecion por 3 dias sin paga', max_length=500),
        ),
        migrations.AlterField(
            model_name='amonestacion',
            name='razon',
            field=models.CharField(help_text='Faltar el respeto a los compañeros del trabajo', max_length=200),
        ),
        migrations.AlterField(
            model_name='energia',
            name='tipo',
            field=models.CharField(help_text='Molino,Panel Solar,etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='ovino',
            name='calidad_de_lana',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ovino',
            name='categoria_por_diente',
            field=models.CharField(choices=[('COR', 'Cordero'), ('BOR', 'Borrego'), ('OVJ', 'Oveja'), ('CAR', 'Carnero')], default='OVJ', max_length=3),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.ForeignKey(default='Killik Aike', on_delete=django.db.models.deletion.CASCADE, to='py.direccion'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='alimento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='py.alimento'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_de_devolucion',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='insumo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='py.insumo'),
        ),
        migrations.AlterField(
            model_name='rodado',
            name='tipo_rodado',
            field=models.CharField(choices=[('CAMIONETA', 'Camioneta'), ('MOTO', 'Moto'), ('TRACTOR', 'Tractor'), ('ESCAVADORA', 'Escavadora'), ('CUATRICICLO', 'Cuatriciclo'), ('OTRO', 'Otro')], default='CAMIONETA', max_length=11),
        ),
    ]
