# Generated by Django 3.1.1 on 2020-11-15 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py', '0014_auto_20201107_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_animal', models.CharField(choices=[('O', 'Ovino'), ('E', 'Equino'), ('A', 'Avicola')], max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='amonestacion',
            old_name='persona',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='energia',
            old_name='tipo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='empleado',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='rodado',
            old_name='Conductores',
            new_name='conductor',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo_prestamo',
            field=models.CharField(choices=[('I', 'Insumo'), ('A', 'Alimento')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='alambrado',
            name='materiales',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='avicola',
            name='raza',
            field=models.CharField(help_text='ponedora', max_length=30),
        ),
        migrations.AlterField(
            model_name='energia',
            name='descripcion_del_estado',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='energia',
            name='fecha_De_mantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.fecha'),
        ),
        migrations.AlterField(
            model_name='equino',
            name='causa_de_muerte',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ovino',
            name='PDP',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ovino',
            name='categoria_por_diente',
            field=models.CharField(choices=[('COR', 'Cordero'), ('BOR', 'Borrego'), ('OVJ', 'Oveja'), ('CAR', 'Carnero'), ('OVJ V', 'Oveja vieja'), ('CAR V', 'Carnero viejo')], default='OVJ', max_length=5),
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='alimento',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='alimento',
            field=models.ManyToManyField(to='py.Alimento'),
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='insumo',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='insumo',
            field=models.ManyToManyField(to='py.Insumo'),
        ),
        migrations.AlterField(
            model_name='equino',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.raza'),
        ),
        migrations.AlterField(
            model_name='ovino',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.raza'),
        ),
    ]
