# Generated by Django 3.1.1 on 2020-11-25 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py', '0016_auto_20201115_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.seccion'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py.direccion'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='tipo_animal',
            field=models.CharField(choices=[('O', 'Ovino'), ('E', 'Equino'), ('A', 'Avicola')], default='O', max_length=1),
        ),
    ]
