# Generated by Django 3.1.1 on 2020-11-26 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('A', 'Animal'), ('H', 'Humano')], default='A', max_length=1)),
                ('fecha_de_compra', models.DateField()),
                ('descripcion_de_cant_individual', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('BUEN_ENSTADO', 'Buen estado'), ('MAL_ESTADO', 'Mal estado'), ('PRESTADO', 'Prestado')], default='BUEN_ENSTADO', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=40)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='O', max_length=1)),
                ('rol', models.CharField(choices=[('DÑ', 'Dueño'), ('ENC', 'Encargado'), ('CZ', 'Capataz'), ('PG', 'Peon General'), ('PC', 'Peon Comun'), ('CAS', 'Casero'), ('PUES', 'Puestero'), ('QUIN', 'Quintero'), ('ESQ', 'Esquilador'), ('COC', 'Cocinero')], default='PC', max_length=4)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.ManyToManyField(to='personal.Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prestamo', models.CharField(choices=[('I', 'Insumo'), ('A', 'Alimento')], default='A', max_length=1)),
                ('fecha_de_entrega', models.DateField()),
                ('fecha_de_devolucion', models.DateField(blank=True)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rodado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=9)),
                ('marca', models.CharField(max_length=20)),
                ('tipo_motor', models.CharField(max_length=20)),
                ('tipo_rodado', models.CharField(choices=[('CAMIONETA', 'Camioneta'), ('MOTO', 'Moto'), ('TRACTOR', 'Tractor'), ('ESCAVADORA', 'Escavadora'), ('CUATRICICLO', 'Cuatriciclo'), ('OTRO', 'Otro')], default='CAMIONETA', max_length=11)),
                ('estado', models.CharField(choices=[('BUEN_ENSTADO', 'Buen estado'), ('MAL_ESTADO', 'Mal estado'), ('EN_MANTENIMIENTO', 'En mantenimiento')], default='BUEN_ENSTADO', max_length=16)),
                ('conductor', models.ManyToManyField(to='personal.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo_Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.alimento')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.prestamo')),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='alimento',
            field=models.ManyToManyField(through='personal.Prestamo_Alimento', to='personal.Alimento'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='insumo',
            field=models.ManyToManyField(to='personal.Insumo'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Enfermo'), ('L', 'Licencia'), ('T', 'Dia trabajado'), ('NT', 'Dia no trabajado')], default='T', max_length=2)),
                ('fecha', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(help_text='Faltar el respeto a los compañeros del trabajo', max_length=200)),
                ('consecuencia', models.CharField(help_text='Suspecion por 3 dias sin paga', max_length=500)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
        ),
    ]
